[project]
name = "pathways-api"
version = "0.1.0"
description = "FastAPI service for pathway analysis (GSEA) for Open Targets"
authors = [{ name = "Open Targets", email = "contact@opentargets.org" }]
readme = "README.md"


requires-python = ">=3.14"
dependencies = [
    "uvicorn>=0.32.0",
    "polars>=1.40.1",
    "duckdb>=1.5.3",
    "loguru>=0.7.3",
    "click>=8.3.1",
    "fastapi>=0.137.1",
    "python-multipart>=0.0.32",
    "pyarrow>=24.0.0",
    "blitzgsea",
]

[dependency-groups]
dev = [
    "ty>=0.0.42",
    "pyinstrument>=5.1.2",
]
lint = ["ruff>=0.7.1"]

[tool.uv.sources]
blitzgsea = { git = "https://github.com/jdhayhurst/blitzgsea", tag = "v0.0.1" }
