name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Install dependencies
      run: uv sync

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: ui/package-lock.json

    - name: Install frontend dependencies
      run: |
        cd ui
        npm ci

    - name: Build frontend
      run: |
        cd ui
        npm run build

    - name: Test Python imports
      run: |
        uv run python -c "import app.main; print('✅ Python imports successful')"

    - name: Test API startup
      run: |
        timeout 10s uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 || true
